# Generated by Django 4.1.3 on 2024-05-12 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='個人_table',
            options={'managed': True},
        ),
    ]
