# Generated by Django 4.1.3 on 2024-05-12 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot_app', '0002_alter_個人_table_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='個人_群組_linktable',
            options={'managed': True},
        ),
    ]
